# Generated by Django 4.0.3 on 2022-04-07 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_question_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answered',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='favorited',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorited_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='favorited',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorited_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
