# Generated by Django 4.0.3 on 2022-04-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(default=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
