# Generated by Django 4.0.3 on 2022-04-13 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_answer_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answered',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='favorited',
            field=models.ManyToManyField(blank=True, related_name='favorited_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_list', to='api.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='favorited',
            field=models.ManyToManyField(blank=True, related_name='favorited_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
